# Site settings
title: Sara McCombs
email: theSaraMcCombs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "saramccombs.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: saramccombs

# Build settings
markdown: kramdown
